Project refactoring
rodi0878/NNPTP22-1 pull request #13
Opened 2022-10-15 19:31 UTC by st61014

2022-10-16 18:40 UTC, rodi0878 requested changes
Please look at comments and provide update

2022-10-16 18:40 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public readonly static ComplexNumber Zero = new ComplexNumber()
Properties should be at the top of class

2022-10-16 18:40 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAbS()
Ab"S"?

2022-10-16 18:40 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAngleInDegrees()
Really degrees?

2022-10-17 11:59 UTC, st61014 commented
requested changes resolved

2022-10-17 16:29 UTC, rodi0878 commented
Accepted

2022-10-17 16:29 UTC, closed without merging