Project refactoring
rodi0878/NNPTP22-1 pull request #14
Opened 2022-10-23 14:49 UTC by st58238

Janáček Lukáš (st58238)

2022-10-27 08:19 UTC, rodi0878 requested changes
Please review comments and provide update

2022-10-27 08:19 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public float ImaginaryPart { get; set; }
why float, if real is double?

2022-10-27 08:19 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public readonly static ComplexNumber Zero = new ComplexNumber()
properties should be at the top of class

2022-10-27 08:19 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAngleInDegrees()
really degrees?

2022-10-27 08:19 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public ComplexNumber Multiply(ComplexNumber b)
reorganize file, math operations should be close together

2022-10-27 08:19 UTC, rodi0878 commented on NNPTPZ1/NewtonFractalGenerator.cs
> +                    Colorize(i, j, FindRoots(ox), Iterate(ox));
this changes the original logic of algorithm!

2022-10-27 08:19 UTC, rodi0878 commented on NNPTPZ1/NewtonFractalGenerator.cs
> +            using (FileStream test = File.OpenWrite(arguments[6] ?? "../../../out.png")) { }
useless

2022-11-08 10:18 UTC, st58238 commented
Implemented requested changes.

2022-11-10 09:04 UTC, rodi0878 commented
accepted

2022-11-10 09:04 UTC, closed without merging