Code refactoring
rodi0878/NNPTP22-1 pull request #19
Opened 2022-11-19 00:30 UTC by st58594

2022-11-20 16:40 UTC, rodi0878 requested changes
please see comments and provide update

2022-11-20 16:40 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public double GetAngleInDegrees()
Really degrees?

2022-11-20 16:40 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        internal ComplexNumber Divide(ComplexNumber b)
Please reorder class and move all math operations to one part, Divide is separated by ToString and Equals...

2022-11-20 16:40 UTC, rodi0878 commented on NNPTPZ1/Mathematics/Polynomial.cs
> +            int i = 0;
why declare and initialize i here?

2022-11-20 16:40 UTC, rodi0878 commented on NNPTPZ1/NewtonFractal.cs
> +        private int FindRoot(ComplexNumber pixel)
Name of method is misleading

2022-11-21 12:31 UTC, st58594 commented
Thank you for the feedback. Updated.

2022-11-23 17:06 UTC, rodi0878 commented
accepted

2022-11-23 17:06 UTC, closed without merging