Code cleanup
rodi0878/NNPTP22-1 pull request #3
Opened 2022-10-05 20:57 UTC by st60994

Václav Hrubý

2022-10-08 14:27 UTC, rodi0878 requested changes
Please look at attached comments and provide update

2022-10-08 14:27 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public float ImaginaryPart { get; set; }
real as double and imaginary as float is nonsense

2022-10-08 14:27 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public ComplexNumber Sum(ComplexNumber b)
Add not Sum

2022-10-08 14:27 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAngleInDegrees()
Really Math.Atan returns degrees?

2022-10-08 14:27 UTC, rodi0878 commented on NNPTPZ1/FractalVisualiser.cs
> +            var actualRootFound = false;
var is not a good option here

2022-10-08 14:27 UTC, rodi0878 commented on NNPTPZ1/FractalVisualiser.cs
> +            var vv = colors[actualRootPosition % colors.Length];
vv?

2022-10-08 14:27 UTC, rodi0878 commented on NNPTPZ1/Polynom.cs
> +            int i = 0;
thats ugly.

2022-10-08 15:13 UTC, st60994 commented
Update with required changes has been provided.

2022-10-12 16:52 UTC, rodi0878 commented
Accepted

2022-10-12 16:52 UTC, closed without merging