Refactoring NNPTPZ1_8_10_2022
rodi0878/NNPTP22-1 pull request #5
Opened 2022-10-08 15:28 UTC by Tomdokx

2022-10-12 16:55 UTC, rodi0878 requested changes
please see mentioned problems and provide update

2022-10-12 16:55 UTC, rodi0878 commented on NNPTPZ1/Program.cs
>          static void Main(string[] args)
method is too complex

2022-10-12 16:55 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +                    float iteration = 0;
why float?

2022-10-12 16:55 UTC, rodi0878 commented on NNPTPZ1/Program.cs
>      namespace Mathematics
separate classes to separate files

2022-10-12 18:44 UTC, Tomdokx commented
More refactored code, problems should be solved.

2022-10-16 18:34 UTC, rodi0878 requested changes

2022-10-16 18:34 UTC, rodi0878 commented on NNPTPZ1/Mathematics/NewtonFractal.cs
> +        public void Draw()
Method is too complex

2022-10-17 16:27 UTC, rodi0878 commented
Accepted

2022-10-17 16:27 UTC, closed without merging